services:
  php:
    build:
      context: ./backend
    container_name: uni_php
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/html/frontend
      - ./backend/apache-uploads.conf:/etc/apache2/conf-available/apache-uploads.conf
    command: /bin/bash -c "a2enconf apache-uploads && apache2-foreground"
    environment:
      DB_HOST: db
      MYSQL_DATABASE: university_portal
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password@1
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:5.7
    container_name: uni_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: university_portal
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password@1
      MYSQL_ROOT_PASSWORD: rootpass@1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-time-zone='+07:00'
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: uni_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
