Alias /uploads/documents/ "/var/www/html/uploads/documents/"
<Directory "/var/www/html/uploads/documents/">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>